import React from 'react';
import { motion } from 'framer-motion';
import { FileText, Users, Shield, Link } from 'lucide-react';

const Term = () => {
    return (
        <motion.div
            className="max-w-8xl mx-auto p-8 bg-white text-gray-800 rounded-lg shadow-xl"
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.8 }}
        >
            <motion.h1
                className="text-4xl font-extrabold text-center text-indigo-600 mb-8"
                initial={{ y: -100 }}
                animate={{ y: 0 }}
                transition={{ type: 'spring', stiffness: 300 }}
            >
                Terms and Conditions
            </motion.h1>

            <div className="space-y-12">
                {/* Introduction Section */}
                <section className="space-y-4">
                    <motion.h2
                        className="text-2xl font-semibold text-indigo-600 flex items-center space-x-3"
                        initial={{ x: -100 }}
                        animate={{ x: 0 }}
                        transition={{ type: 'spring', stiffness: 300 }}
                    >
                        <FileText className="w-6 h-6 text-indigo-600" />
                        <span>Welcome to SocyGen!</span>
                    </motion.h2>
                    <p className="text-lg text-gray-700">
                        These Terms and Conditions govern your use of our website, https://SocyGen.com (the "Website"), and outline the agreement between you (the "User") and us (SocyGen). By accessing or using our Website, you agree to comply with these Terms and our Privacy Statement. Please review them carefully. If you disagree with any part of these Terms or our Privacy Statement, we kindly ask you to refrain from using our Website.
                    </p>
                    <p className="text-lg text-gray-700">
                        We may update these Terms and our Website's content at any time without prior notice.
                    </p>
                </section>

                {/* Certificates Section */}
                <section className="space-y-4">
                    <motion.h2
                        className="text-2xl font-semibold text-indigo-600 flex items-center space-x-3"
                        initial={{ x: -100 }}
                        animate={{ x: 0 }}
                        transition={{ type: 'spring', stiffness: 300 }}
                    >
                        <Shield className="w-6 h-6 text-indigo-600" />
                        <span>Certificates</span>
                    </motion.h2>
                    <p className="text-lg text-gray-700">
                        At SocyGen, we offer optional paid Certificates and Diplomas to acknowledge your achievements.
                    </p>
                    <ul className="list-inside list-disc space-y-4 text-gray-700 mt-4">
                        <li><strong>Certificate Formats:</strong> Digital (PDF), Parchment (physical document), or Framed Parchment (framed physical document).</li>
                        <li><strong>Delivery:</strong> Digital Certificates are available for instant download. Parchment options shipped via Standard or Express Shipping (fee applies).</li>
                        <li><strong>Academic Transcript:</strong> A detailed summary with your course scores and an authentication link.</li>
                        <li><strong>Design Changes:</strong> We may update Certificate designs periodically. Review templates in our Shop before purchase to ensure satisfaction.</li>
                    </ul>
                </section>

                {/* Affiliates Section */}
                <section className="space-y-4">
                    <motion.h2
                        className="text-2xl font-semibold text-indigo-600 flex items-center space-x-3"
                        initial={{ x: -100 }}
                        animate={{ x: 0 }}
                        transition={{ type: 'spring', stiffness: 300 }}
                    >
                        <Users className="w-6 h-6 text-indigo-600" />
                        <span>Affiliates</span>
                    </motion.h2>
                    <p className="text-lg text-gray-700">
                        SocyGen reserves the right to refuse registration or suspend participation in our affiliate program.
                    </p>
                    <ul className="list-inside list-disc space-y-4 text-gray-700 mt-4">
                        <li><strong>Commission:</strong> Earn a 20% marketing referral fee from traffic and income generated by new learners.</li>
                        <li><strong>Payment:</strong> Payments are made monthly, with a minimum threshold of 100 euros. Below threshold carries over to the next month.</li>
                    </ul>
                </section>

                {/* Business Section */}
                <section className="space-y-4">
                    <motion.h2
                        className="text-2xl font-semibold text-indigo-600 flex items-center space-x-3"
                        initial={{ x: -100 }}
                        animate={{ x: 0 }}
                        transition={{ type: 'spring', stiffness: 300 }}
                    >
                        <Link className="w-6 h-6 text-indigo-600" />
                        <span>SocyGen Business</span>
                    </motion.h2>
                    <ul className="list-inside list-disc space-y-4 text-gray-700 mt-4">
                        <li><strong>Advertisements:</strong> We include standard advertisements on the platform. Removal is available as a premium service.</li>
                        <li><strong>Certification:</strong> Only SocyGen certifications may be issued for courses integrated into API Client systems.</li>
                    </ul>
                </section>

                {/* Abuse Policy Section */}
                <section className="space-y-4">
                    <motion.h2
                        className="text-2xl font-semibold text-indigo-600 flex items-center space-x-3"
                        initial={{ x: -100 }}
                        animate={{ x: 0 }}
                        transition={{ type: 'spring', stiffness: 300 }}
                    >
                        <Shield className="w-6 h-6 text-indigo-600" />
                        <span>Abuse Policy</span>
                    </motion.h2>
                    <p className="text-lg text-gray-700">
                        Respectful behavior is expected at all times. Prohibited conduct includes defamatory remarks, offensive content, privacy breaches, and illegal activities.
                    </p>
                </section>

                {/* Limits of Use Section */}
                <section className="space-y-4">
                    <motion.h2
                        className="text-2xl font-semibold text-indigo-600 flex items-center space-x-3"
                        initial={{ x: -100 }}
                        animate={{ x: 0 }}
                        transition={{ type: 'spring', stiffness: 300 }}
                    >
                        <Link className="w-6 h-6 text-indigo-600" />
                        <span>Limits of Use</span>
                    </motion.h2>
                    <ul className="list-inside list-disc space-y-4 text-gray-700 mt-4">
                        <li><strong>Lawful Use:</strong> Use the Website only for lawful purposes, avoiding fraudulent or unlawful activities.</li>
                        <li><strong>Additional Restrictions:</strong> No unauthorized reproduction, resale, or charging for access unless agreed upon.</li>
                    </ul>
                </section>

                {/* Social Media Section */}
                <section className="space-y-4">
                    <motion.h2
                        className="text-2xl font-semibold text-indigo-600 flex items-center space-x-3"
                        initial={{ x: -100 }}
                        animate={{ x: 0 }}
                        transition={{ type: 'spring', stiffness: 300 }}
                    >
                        <Users className="w-6 h-6 text-indigo-600" />
                        <span>Social Media</span>
                    </motion.h2>
                    <p className="text-lg text-gray-700">
                        SocyGen reserves the right to screen, edit, or remove content from our social media platforms at our discretion.
                    </p>
                    <p className="text-lg text-gray-700">
                        Users must be 16 years or older to engage with SocyGen's social media accounts.
                    </p>
                </section>

                {/* Termination Section */}
                <section className="space-y-4">
                    <motion.h2
                        className="text-2xl font-semibold text-indigo-600 flex items-center space-x-3"
                        initial={{ x: -100 }}
                        animate={{ x: 0 }}
                        transition={{ type: 'spring', stiffness: 300 }}
                    >
                        <Shield className="w-6 h-6 text-indigo-600" />
                        <span>Termination</span>
                    </motion.h2>
                    <p className="text-lg text-gray-700">
                        We may deactivate your account at our discretion. You may also deactivate your account, but we will retain course tracking history in our database.
                    </p>
                </section>

                {/* Footer Section */}
                <footer className="mt-12 text-center text-gray-600 text-sm">
                    <p>Thank you for being part of SocyGen. We’re here to support your learning journey and ensure a respectful, productive environment for all users.</p>
                </footer>
            </div>
        </motion.div>
    );
};

export default Term;
